#!/bin/sh

# These are udev rules and scripts that are placed here for the sake of readability 
# later in this script.
no_systemd_mount_rules=$(cat <<'EOM'
# Only try to automount DO block volumes.
SUBSYSTEM!="block", GOTO="do_automount_end"
ENV{ID_VENDOR}!="DO", GOTO="do_automount_end"
ENV{ID_MODEL}!="Volume", GOTO="do_automount_end"
# Only automount on the "add" action.
ACTION!="add", GOTO="do_automount_end"
# Only try to automount filesystems we know about.
ENV{ID_FS_TYPE}!="ext4|xfs", GOTO="do_automount_end"

# Create a temporary mountpoint and temporary location for the first-mount script.
IMPORT{program}="/bin/sh -c 'echo TMP_MOUNT_DIR=$(mktemp -d -p /mnt .do-first-mount-XXXXXXXXX)'"
# Handle temporary mountpoint creation failure.
ENV{TMP_MOUNT_DIR}=="", GOTO="do_automount_end"
IMPORT{program}="/bin/sh -c 'echo TMP_SCRIPT=$(mktemp -t .do-first-mount-XXXXXXXXX.sh)'"
# Handle temporary script location creation failure.
ENV{TMP_SCRIPT}=="", PROGRAM="/bin/sh -c '/bin/rmdir %E{TMP_MOUNT_DIR} || exit 0'", GOTO="do_automount_end"

# Mount the volume at the temp mountpoint and copy the script off, then unmount.
RUN{program}+="/bin/mount -o ro /dev/%k %E{TMP_MOUNT_DIR}"
RUN{program}+="/bin/sh -c '/bin/cp %E{TMP_MOUNT_DIR}/.first-mount.sh %E{TMP_SCRIPT} || exit 0'"
RUN{program}+="/bin/umount %E{TMP_MOUNT_DIR}"
RUN{program}+="/bin/rmdir %E{TMP_MOUNT_DIR}"

# Run the first-mount script. If it didn't exist this will be a no-op.
RUN{program}+="/bin/sh %E{TMP_SCRIPT} '%E{ID_SERIAL}' '%E{ID_FS_TYPE}' '%E{ID_SERIAL_SHORT}' '%E{ID_FS_UUID}' '%E{ID_FS_LABEL}'"

# Clean up.
RUN{program}+="/bin/rm %E{TMP_SCRIPT}"

# Finally, try and mount the volume. On first mount this will fail, but that's
# OK because the volume was already mounted by the first-mount script.
RUN{program}+="/bin/sh -c '/bin/mount /dev/%k || exit 0'"

LABEL="do_automount_end"
EOM
)

systemd_mount_rules=$(cat <<'EOM'
# Only try to automount DO block volumes.
SUBSYSTEM!="block", GOTO="do_automount_end"
ENV{ID_VENDOR}!="DO", GOTO="do_automount_end"
ENV{ID_MODEL}!="Volume", GOTO="do_automount_end"

# Only automount on "add" or "change" actions.
ACTION!="add|change", GOTO="do_automount_end"
# Only try to automount filesystems we know about.
ENV{ID_FS_TYPE}!="ext4|xfs", GOTO="do_automount_end"

# Create a temporary location for the first-mount script.
IMPORT{program}="/bin/sh -c 'echo TMP_SCRIPT=$$(mktemp -t .do-first-mount-XXXXXXXXX.sh)'"
# Handle temporary script location creation failure.
ENV{TMP_SCRIPT}=="", GOTO="do_automount_end"

RUN{program}+="/var/lib/cloud/scripts/per-instance/systemd_automount.sh %k %E{TMP_SCRIPT} '%E{ID_SERIAL}' '%E{ID_FS_TYPE}' '%E{ID_SERIAL_SHORT}' '%E{ID_FS_UUID}' '%E{ID_FS_LABEL}'"

LABEL="do_automount_end"
EOM
)

systemd_mount_script=$(cat <<'EOM'
#!/bin/bash

DEVICE=$1
TMP_SCRIPT=$2
ID_SERIAL=$3
ID_FS_TYPE=$4
ID_SERIAL_SHORT=$5
ID_FS_UUID=$6
ID_FS_LABEL=$7

function cleanup() {
   if [ -f "${TMP_SCRIPT}" ]; then
      rm -f "${TMP_SCRIPT}"
   fi
}

trap cleanup EXIT

# If device is blank or unset exit. Can happen on first start
if [ -z "$DEVICE" ]; then
    exit 0
fi

devpath="/dev/${DEVICE}"

# New first-mount approach
magic_size=14
size=$(( 512 * $(cat /sys/block/${DEVICE}/size) ))
offset=$(( ${size} - ${magic_size} ))
magic=$(dd if="${devpath}" bs=${magic_size} count=1 skip=${offset} iflag=skip_bytes 2>/dev/null | tr -d '\000')

if [ "${magic}" == "DO_FIRST_MOUNT" ]; then
   logger -t digitalocean-automount "detected first mount magic"

   # Clear magic so this script won't trigger again
   dd if=/dev/zero of="${devpath}" bs=${magic_size} count=1 seek=${offset} oflag=seek_bytes 2>/dev/null

   # First mount trailer format:
   # <script body>
   # <metadata>
   # <script size - 7 bytes>
   # <metadata size - 6 bytes>
   # DO_FIRST_MOUNT
   # <end-of-disk>

   # Metadata is a list of key=value pairs separated by ';'
   # Available metadata keys:
   # fs=<string>      - filesystem type [required]
   # md5=<string>     - script md5 schecksum
   
   md_header_size=6
   script_header_size=7
   
   # DO_FIRST_MOUNT (14 bytes)
   offset=$(( ${size} - ${magic_size} - ${md_header_size} ))
   
   # Metadata size (6 bytes)
   md_size=$(dd if="${devpath}" bs=${md_header_size} count=1 skip=${offset} iflag=skip_bytes 2>/dev/null | tr -d '\000')
   offset=$((${offset} - ${script_header_size}))
   
   # Script size (7 bytes)
   script_size=$(dd if="${devpath}" bs=${script_header_size} count=1 skip=${offset} iflag=skip_bytes 2>/dev/null | tr -d '\000')
   offset=$((${offset} - ${md_size}))
   
   # Metadata
   md=$(dd if="${devpath}" bs="${md_size}" count=1 skip=${offset} iflag=skip_bytes 2>/dev/null | tr -d '\000')
   offset=$((${offset} - ${script_size}))
   
   # Script
   script=$(dd if="${devpath}" bs="${script_size}" count=1 skip=${offset} iflag=skip_bytes 2>/dev/null | tr -d '\000')
   
   # Parse metadata
   md_fs=""
   md_md5=""
   
   IFS=';' read -ra MD <<< "${md}"
   for i in "${MD[@]}"; do
      key=$(echo "${i}" | cut -f1 -d'=')
      value=$(echo "${i}" | cut -f2 -d'=')
   
      case ${key} in
         fs)
            md_fs=$value
            ;;
         md5)
            md_md5=$value
            ;;
         *)
            export "DO_FIRST_MOUNT_${key}=${value}"
      esac
   done
   
   if [ -z "${md_fs}" ]; then
      logger -t digitalocean-automount -p user.err "required metadata key not set: fs"
      exit 1
   fi
   
   # Verify script checksum if provided
   if [ -n "${md_md5}" ]; then
      script_md5=$(echo "${script}" | md5sum | cut -f1 -d" ")
   
      if [ "${script_md5}" != "${md_md5}" ]; then
         logger -t digitalocean-automount -p user.err "script checksum mismatch: ${script_md5} (actual) != ${md_md5} (expected)"
         exit 1;
      else
         logger -t digitalocean-automount "script checksum verified"
      fi
   fi
   
   # Copy script to a temporary location
   echo "${script}" > "${TMP_SCRIPT}"
   chmod 755 "${TMP_SCRIPT}"
   
   # Execute first mount script
   if [ $(command -v systemd-run) ]; then
      systemd-run -G --no-block --scope /bin/sh "${TMP_SCRIPT}" "${ID_SERIAL}" "${md_fs}" "${ID_SERIAL_SHORT}" "${ID_FS_UUID}" "${ID_FS_LABEL}"
   else
      /bin/sh "${TMP_SCRIPT}" "${ID_SERIAL}" "${md_fs}" "${ID_SERIAL_SHORT}" "${ID_FS_UUID}" "${ID_FS_LABEL}"
   fi
fi
EOM
)

# Disable the locale warning: by default imported cloud-images check the default
# local and give a warning about invalid locales. The following line disable
# the warning.

# do not assume that /etc/skel exists
if [ -d /etc/skel ]; then
    touch /etc/skel/.cloud-locale-test.skip
fi
touch /root/.cloud-locale-test.skip

# Disable Ubuntu MOTD
if [ -f /etc/default/motd-news ]; then
    sed -e "s/ENABLED=1/ENABLED=0/g" \
        -i /etc/default/motd-news
fi

# Fix buggy cloud-init routes for IPv6
r6c="/etc/sysconfig/network-scripts/route6-eth0"
if [ -f "${r6c}" ]; then
    sed -e "s|::/::|default|g" -i "${r6c}"
    awk '/default via/{system("ip -6 route add default via "$NF" dev eth0")}' "${r6c}"
elif [ -d "/etc/sysconfig/network-scripts" -a -f "/etc/network/interfaces" ]; then
    # This deals with a bug in Fedora 27 where the network interface is not set
    # properly by Cloud-init.
    i6gw=$(egrep -A3 'iface eth0:1 inet6 static' /etc/network/interfaces | awk '/gateway/{print$NF}')
    if [ -n "${i6gw}" ]; then
        ip -6 route add default via ${i6gw} dev eth0
        cat > ${r6c} <<EOM
# DigitalOcean: written by ConfigDrive customization.
default via ${i6gw}
EOM
    fi
fi

# Fix screwy file permmissions on the system resolvers.
chmod 0644 /etc/resolv.conf

# Support automatic disk resizing per boot.
# Only update /etc/hosts once per instance.
mkdir -p /etc/cloud/cloud.cfg.d
cat > /etc/cloud/cloud.cfg.d/90-digitalocean.cfg <<EOM
####
# DigitalOcean: this file was written via cloud-init and composed from /etc/cloud/cloud.cfg
#               In order to support resize events, 'growpart' and 'resizefs' are run each boot.
#               'update_etc_hosts' will be run only once per instance. To see the differences, run
#               'diff -u /etc/cloud/cloud.cfg /etc/cloud/cloud.cfg.d/90-digitalocean.cfg'.
#
#               This file was written to support Droplet $(</sys/devices/virtual/dmi/id/product_serial) on $(date +%Y-%m-%d)
####

EOM
sed -e "s/- growpart$/- [ growpart, always ]/g" \
    -e "s/- resizefs$/- [ resizefs, always ]/g" \
    -e "s/- update_etc_hosts$/- [ update_etc_hosts, once-per-instance ]/g" \
    /etc/cloud/cloud.cfg >> /etc/cloud/cloud.cfg.d/90-digitalocean.cfg

# Fix for machine-id's being dubiously present
cat > /var/lib/cloud/scripts/per-instance/machine_id.sh <<EOM
#!/bin/bash
CT=\$(date +%s);
FT=\$(stat /etc/machine-id -c %Y);
DIFF=\$(expr \$CT - \$FT)
# record timestamp on machine-id for testing
# If /etc/machine_id is over 10m old on first-boot, delete it
if [ -f /etc/machine-id ]; then
    if [ \$DIFF -lt 600 ]; then
        exit 0
    fi
rm -rf /etc/machine-id
fi

# systemd will use dbus uudigen if its there
# we need to reset this for Debain 9.
if which dbus-uuidgen &> /dev/null; then
    rm -rf /var/lib/dbus/machine-id
    dbus-uuidgen --ensure=/var/lib/dbus/machine-id
fi

if which systemd-machine-id-setup &> /dev/null; then
    rm -rf /etc/machine-id
    systemd-machine-id-setup
fi
EOM
chmod 0700 /var/lib/cloud/scripts/per-instance/machine_id.sh

# DigitalOcean updated the vendor-data to better support various distributions.
# This script makes it so older snapshots will work by restoring the default behavior
# of cloud-init.
if [ -e /etc/cloud/cloud.cfg.disabled ]; then
    mv /etc/cloud/cloud.cfg /etc/cloud/cloud.cfg.d/99-digitalocean.cfg
    mv /etc/cloud/cloud.cfg.disabled /etc/cloud/cloud.cfg
    logger -t DigitalOcean "restored default cloud-init behavior by renaming /etc/cloud/cloud.cfg.disabled to /etc/cloud/cloud.cfg"
fi

# Newer versions of systemd-udevd behave badly when trying to run the original udev rules.
# Using mount in udev is highly discouraged and behaves poorly when systemd-mount is available
# The script enforces serialization of commands without changing udev settings
# See BLOCK-1832
if [ -d /etc/udev/rules.d ]; then
    if command -v systemd-mount > /dev/null 2>&1 && command -v systemd-umount > /dev/null 2>&1; then
        # Add udev rules to automount block storage volumes using systemd-mount.
        /bin/echo "$systemd_mount_rules" > /etc/udev/rules.d/99-digitalocean-automount.rules
        /bin/echo "$systemd_mount_script" > /var/lib/cloud/scripts/per-instance/systemd_automount.sh
        chmod 0700 /var/lib/cloud/scripts/per-instance/systemd_automount.sh
    else
        # Add udev rules to automount block storage volumes.
        /bin/echo "$no_systemd_mount_rules" > /etc/udev/rules.d/99-digitalocean-automount.rules
    fi

    # Some versions of systemd-udevd end up in a weird state when we add and
    # trigger rules on-the-fly, as below. Restarting the service seems to
    # resolve things. See BLOCK-1435 for details.
    if command -v systemctl > /dev/null 2>&1; then
        systemctl restart systemd-udevd.service
    fi

    # Load the newly-added udev rules and then manually trigger them to catch
    # any automount volumes that were attached at boot.
    if command -v udevadm > /dev/null 2>&1; then
        udevadm control -R
        if command -v systemd-mount > /dev/null 2>&1 && command -v systemd-umount > /dev/null 2>&1; then
            udevadm trigger --action=change --subsystem-match=block
        else
            udevadm trigger --action=add --subsystem-match=block
        fi
    fi
fi

